### ISSUE TITLE
tree view cut off at bottom

### ISSUE THREAD

**Issue by hdliv** [phylotastic/Pt_Mobile_Application#73] opened 2016-03-28 15:34 UTC
i wasn't able to reproduce this but wanted to document it in case we see it again.  We should be able to export both our list of species and tree .  I will create another issue for exporting list.

located here: Pt_Mobile_Application/test/images/odd_tree.jpg

**Comment by arlin** [comment] 2016-03-31 14:29
I have seen this behavior as well, and I think this is related to #75.  In #75 this is described as a problem with a larger tree.  However, perhaps it is simply the case that the viewer is choosing the wrong frame size and fails to show the branch at the bottom of the tree image.

**Comment by hdliv** [comment] 2016-03-31 14:32
in #67 I also speak of this behaviour

**Comment by arlin** [comment] 2016-03-31 15:53
In the attached image, you can see that this is a matter of the frame being off, because the upper part of the missing name is visible (circled area)
![frame_issue](https://cloud.githubusercontent.com/assets/1659198/14181918/181b8d9c-f737-11e5-97f6-fc53f373257b.png)

**Comment by hdliv** [comment] 2016-04-05 12:19
@arlin when i export to browser, the full tree with no cut-off is viewed

**Comment by thanhnh-infinity** [comment] 2016-04-06 21:21
Yes @hdliv , It is only in app. I am trying to fix it. But unfortunately, it is issue that comes from origin jsphylosvg library. So, I need to do some more researches in the case we are continue using jsphylosvg
There are some references links:
https://jsphylosvg.uservoice.com/forums/55902-general/suggestions/7252947-clear-and-reload-tree
http://stackoverflow.com/questions/30667884/why-is-the-bottom-of-the-figure-cut-off

**Comment by hdliv** [comment] 2016-04-07 18:40
@thanhnh-infinity thanks for the explanation

**Comment by hdliv** [comment] 2016-04-19 18:45
moving this since we have identified the problem.  is that ok @thanhnh-infinity

**Comment by arlin** [comment] 2016-04-21 21:31
I posted a comment about this on the jsphylosvg site.   I also wrote to the author.  I met him when he first presented a demo of jsphylosvg at iEvoBio.

**Comment by arlin** [comment] 2016-07-22 14:51
Sorry for not following up on this.  SS (original developer) wrote back to me and says  "If you're able to generate a page that reproduces this for me that would be very helpful.

Have you by any chance tried to adjust the height property? "

**Comment by thanhnh-infinity** [comment] 2016-09-01 07:16
I have not changed the height property. jsphylosvg is javascript, works only on Web. In order to work on our mobile app, I had to re-code everything based on jsphylosvg features because the app's language in iOS is Objective-C and Android is JAVA. I tried to search solution but I think it is not solved yet. I sent link to download our application to the author.

**Comment by hdliv** [comment] 2016-09-01 16:19
@thanhnh-infinity thank you.  I received the notice.

**Comment by arlin** [comment] 2016-09-13 14:33
I do not see this problem anymore.   @hdliv, are you still seeing this?

**Comment by hdliv** [comment] 2016-09-13 14:42
@arlin OK for me

**Comment by arlin** [comment] 2016-09-13 14:56
closing

**Closed as completed** 2016-09-13 14:56 UTC
Labels: bug
